language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
install:
  - pip install -r requirement/core.txt
  - pip install -r requirement/test.txt
script:
  - python setup.py test
after_success:
  - coveralls
