language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - pep8 layered test
  - py.test --cov=layered test
after_success:
  - if [[ $ENV == python=3.5* ]]; then coveralls; fi
