language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - pep8 layered test
  - py.test test
after_success:
  - coveralls
