language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
install:
  - pip install setuptools
  - python setup.py install
script:
  - python setup.py test
after_success:
  # Upload coverage reports of one build only
  - if [[ $ENV == python=3.5* ]]; then coveralls; fi
