dataset: Mnist
cost: CrossEntropy
layers:
  - activation: Linear
    size: 784
  - activation: Softmax
    size: 10
training_rounds: 1
batch_size: 1
learning_rate: 0.1
momentum: 0
weight_scale: 0.01
weight_decay: 0
evaluate_every: 1000
