dataset: Classification
cost: CrossEntropy
layers:
  - activation: Linear
    size: 20
  - activation: Sigmoid
    size: 50
  - activation: Softmax
    size: 5
epochs: 1
batch_size: 1
learning_rate: 0.1
momentum: 0
weight_scale: 0.01
weight_decay: 0
evaluate_every: 200
