dataset: Mnist
cost: Squared
layers:
  - activation: Linear
    size: 784
  - activation: Relu
    size: 700
  - activation: Relu
    size: 300
  - activation: Sigmoid
    size: 10
training_rounds: 5
batch_size: 10
learning_rate: 0.1
momentum: 0.5
weight_scale: 0.01
weight_decay: 1e-3
evaluate_every: 10000
