dataset: Mnist
cost: CrossEntropy
layers:
- activation: Identity
  size: 784
- activation: Relu
  size: 700
- activation: Relu
  size: 700
- activation: Relu
  size: 400
- activation: Softmax
  size: 10
<<<<<<< HEAD
=======
initial_weights:
  type: Xavier
  distribution: Normal
  scale: 0.1
learning_rate:
  type: Constant
  rate: 0.01
>>>>>>> Add first version of problem parser
epochs: 5
batch_size: 32
momentum: 0.9
weight_decay: 0
evaluate_every: 5000
