dataset: Modulo
cost: CrossEntropy
layers:
  - activation: Linear
    size: 32
  - activation: Relu
    size: 64
  - activation: Relu
    size: 64
  - activation: Softmax
    size: 7
epochs: 1
learning_rate: 0.008
weight_scale: 0.1
evaluate_every: 5000
