dataset: Regression
cost: Squared
layers:
  - activation: Linear
    size: 10
  - activation: Relu
    size: 20
  - activation: Softmax
    size: 2
epochs: 1
learning_rate: 0.1
weight_scale: 0.1
evaluate_every: 500
